sonar.projectKey=Delivera-Project_Delivera
sonar.organization=delivera-project-delivera
sonar.host.url=https://sonarcloud.io
sonar.projectName=Delivera

sonar.sources=backend/src/main/java,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js,**/*.test.js
sonar.java.source=21
sonar.java.binaries=backend/target/classes
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/config/**,**/dto/**,**/model/**,**/exception/**
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
