ALTER TABLE companies ALTER COLUMN activity_type TYPE VARCHAR(50) USING activity_type::VARCHAR;
ALTER TABLE workers ALTER COLUMN role TYPE VARCHAR(50) USING role::VARCHAR;
ALTER TABLE operational_units ALTER COLUMN type TYPE VARCHAR(50) USING type::VARCHAR;
ALTER TABLE orders ALTER COLUMN status TYPE VARCHAR(50) USING status::VARCHAR;
